[package]
name = "aoc_2019"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
md-5 = "0.9.1"
itertools = "0.9.0"
regex = "1.6.0"
serde_json = "1.0.61"