[package]
name = "day07"
version = "0.1.0"
authors = ["nicoambrosini <nico.ambrosini14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
