name: Rust

on:
  push:
    branches: [ main, 2018 ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build -- 2018
      run: cargo build --verbose
      working-directory: 2018
    - name: Run tests -- 2018
      run: cargo test --verbose
      working-directory: 2018