name: aoc-2019

on:
  push:
    branches: [ main, 2019 ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build -- 2019
      run: cargo build --verbose
      working-directory: 2019
    - name: Run tests -- 2019
      run: cargo test --verbose
      working-directory: 2019