name: format
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
env:
  CARGO_TERM_COLOR: always
jobs:
  fmt-2015:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            aoc_2015:
              - '2015/**'
            aoc_2016:
              - '2016/**'
            aoc_2017:
              - '2017/**'
            aoc_2018:
              - '2018/**'
            aoc_2019:
              - '2019/**'
            aoc_2020:
              - '2020/**'
            aoc_2021:
              - '2021/**'
            aoc_2022:
              - '2022/**'
      - name: format-2015
        if: steps.filter.outputs.aoc_2015 == 'true'
        run: cargo fmt
        working-directory: "2015"
      - name: format-2016
        if: steps.filter.outputs.aoc_2016 == 'true'
        run: cargo fmt
        working-directory: "2016"
      - name: format-2017
        if: steps.filter.outputs.aoc_2017 == 'true'
        run: cargo fmt
        working-directory: "2017"
      - name: format-2018
        if: steps.filter.outputs.aoc_2018 == 'true'
        run: cargo fmt
        working-directory: "2018"
      - name: format-2019
        if: steps.filter.outputs.aoc_2019 == 'true'
        run: cargo fmt
        working-directory: "2019"
      - name: format-2020
        if: steps.filter.outputs.aoc_2020 == 'true'
        run: cargo fmt
        working-directory: "2020"
      - name: format-2021
        if: steps.filter.outputs.aoc_2021 == 'true'
        run: cargo fmt
        working-directory: "2021"
      - name: format-2022
        if: steps.filter.outputs.aoc_2022 == 'true'
        run: cargo fmt
        working-directory: "2022"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cargo fmt changes

