name: test
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test-2015
        run: cargo test
        working-directory: "2015"
      - name: test-2016
        run: cargo test
        working-directory: "2016"
      - name: test-2017
        run: cargo test
        working-directory: "2017"
      - name: test-2018
        run: cargo test
        working-directory: "2018"
      - name: test-2019
        run: cargo test
        working-directory: "2019"
      - name: test-2020
        run: cargo test
        working-directory: "2020"
      - name: test-2021
        run: cargo test
        working-directory: "2021"
      - name: test-2022
        run: cargo test
        working-directory: "2022"
