name: test
on: [push]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            2015:
              - '2015/**'
            2016:
              - '2016/**'
            2017:
              - '2017/**'
            2018:
              - '2018/**'
            2019:
              - '2019/**'
            2020:
              - '2020/**'
            2021:
              - '2021/**'
            2022:
              - '2022/**'
      - name: test-2015
        if: steps.filter.outputs.2015 == 'true'
        run: cargo test
        working-directory: "2015"
      - name: test-2016
        if: steps.filter.outputs.2016 == 'true'
        run: cargo test
        working-directory: "2016"
      - name: test-2017
        if: steps.filter.outputs.2017 == 'true'
        run: cargo test
        working-directory: "2017"
      - name: test-2018
        if: steps.filter.outputs.2018 == 'true'
        run: cargo test
        working-directory: "2018"
      - name: test-2019
        if: steps.filter.outputs.2019 == 'true'
        run: cargo test
        working-directory: "2019"
      - name: test-2020
        if: steps.filter.outputs.2020 == 'true'
        run: cargo test
        working-directory: "2020"
      - name: test-2021
        if: steps.filter.outputs.2021 == 'true'
        run: cargo test
        working-directory: "2021"
      - name: test-2022
        if: steps.filter.outputs.2022 == 'true'
        run: cargo test
        working-directory: "2022"
